### ISSUE TITLE
 README.md tutorial is not working

### ISSUE THREAD

**Issue by kuromike0629** [pottava/trivy-restapi#1]
I tried to run trivy-restapi following README.md.

Run command
$ docker run --name trivy -d --rm -p 9000:9000 \
    -v "${HOME}/Library/Caches":/root/.cache/ \
    pottava/trivy:0.0.16

$ curl -s -X GET -H 'Content-Type:application/json' \
  "http://localhost:9000/api/v1/images/python%3A3.4.10-alpine3.9/vulnerabilities" \
  | jq .

Return code
2019/05/22 02:25:23 [172.17.0.1:46952] 0.000 GET /api/v1/images/python%5C/3.6-alpine3.9/vulnerabilities
2019/05/22 02:26:23 exit status 1

{"code":"400","message":"Bad Request"}

**Comment by pottava** [comment]
@kuromike0629 Sorry about that. I think I've resolved it. Could you try again?

**Comment by kuromike0629** [comment]
Thanks!! Now It works :)
