### ISSUE TITLE
How to use this repo after I have deployed trivy

### ISSUE THREAD

**Issue by tuhaolam** [pottava/trivy-restapi#2]
Thanks to pottava's great work. But I am confusing how  to use this repo after I have deployed trivy? Or may I just need this repo without trivy installed?

**Comment by pottava** [comment]
@tuhaolam Thank you for being interested in it. Yes, you don't have to deploy Trivy. This repo includes not only the REST API server but also Trivy itself and a database for it. All you have to do is to run this docker image 'pottava/trivy:0.1'. However I did not maintain this repo recently, so please feel free to ask me if it does not work properly.
